name: Daily refresh
on:
  schedule:
    - cron: "0 15 * * *"
  push:
    branches:
      - daily
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch origin www daily main
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GHA_DEPLOY_KEY }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: ./gha.py -cfp -b main -b www
