name: Daily refresh
on:
  schedule:
    - cron: "10 15 * * *"
  push:
    branches:
      - daily
      - test
  workflow_dispatch:
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Check current branch
        run: git symbolic-ref -q --short HEAD
      - name: Fetch history
        run: |
          year=$(date +%Y)
          git fetch --shallow-since $year-01-01 origin
      - name: Show all history
        run: git log '--format=%h%d %ad %s' --date=local --graph --all
      - name: Show HEAD history
        run: git log '--format=%h%d %ad %s' --date=local --graph
      - run: git fetch --depth=2 origin
      - name: Show HEAD history
        run: git log '--format=%h%d %ad %s' --date=local --graph
