name: Daily refresh
on:
  schedule:
    - cron: "0 15 * * *"
  push:
    branches:
      - daily
  workflow_dispatch:
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GHA_DEPLOY_KEY }}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: pip
      - run: pip install -e .
      - id: refresh_data
        run: njsp -ac refresh_data
      - id: update_pqts
        if: steps.refresh_data.outputs.sha
        run: njsp -c update_pqts
      - id: update_plots
        if: steps.update_pqts.outputs.sha
        run: njsp -cc update_plots
      - if: steps.update_plots.outputs.sha
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: www/yarn.lock
      - if: steps.update_plots.outputs.sha
        name: npm install, build, export
        run: |
          cd www
          npm install
          npm run gha-export
      - if: steps.update_plots.outputs.sha
        name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: www/out
    outputs:
      update_pqts: ${{ steps.update_pqts.outputs.sha }}
  post:
    name: Call Slack-post workflow
    needs: refresh
    if: needs.refresh.outputs.update_pqts != ''
    uses: ./.github/workflows/slack-test.yml
    with:
      commits: ${{ needs.refresh.outputs.update_pqts }}
    secrets: inherit
