name: Post commit summaries to Slack
on:
  workflow_dispatch:
    inputs:
      commits:
        description: Commit refs to print summaries for
        default: 22b52f3 3e6d22a 39a673b
jobs:
  post:
    name: Post commit summaries to Slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: pub
      - uses: actions/setup-python@v4
        with:
          cache: pip
      - run: pip install -e .
      - run: pip list
      - name: Compute commit summaries
        id: summaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'slack_payload<<EOF' >> $GITHUB_OUTPUT
          commit-crashes --slack ${{ inputs.commits }} >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: "${{ steps.summaries.outputs.slack_payload }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
