name: Print commit summaries
on:
  workflow_dispatch:
    inputs:
      commits:
        description: Commit refs to print summaries for
        default: 22b52f3 3e6d22a 39a673b
      depth:
        default: 10
        type: number
        description: Checkout depth
jobs:
  post:
    name: Publish to Slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.depth }}
      - uses: actions/setup-python@v4
        with:
          cache: pip
      - run: |
          git fetch origin --depth=1 $(git log --no-walk --format=%H ${{ inputs.commits }})
      - run: pip install -e .
      - run: commit_crashes --help
      - name: Compute commit summaries
        id: summaries
        run: |
          echo 'slack_payload<<EOF' >> $GITHUB_OUTPUT
          commit_crashes --slack ${{ inputs.commits }} >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: "${{ steps.summaries.outputs.slack_payload }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
